In [1]:
import config
import preprocessing  as p
import postprocessing as m
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from scipy.stats import zscore
import numpy as np
from keras.models import load_model
import numpy as np
import matplotlib as mpl
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, log_loss, cohen_kappa_score, matthews_corrcoef
import pandas as pd
import os
import config
from sklearn.preprocessing import StandardScaler
from keras.models import clone_model


In [2]:
server='/Volumes/EEG Core HD/Pipeline For Olga/Pipeline Example Files/Mats/'
path='/Users/Olga/CS_projects/SWISC/package/datanpy_newest_scored/Feats_Fourier_and_PSD'
path_1='/Volumes/EEG Core HD/Pipeline For Olga/Pipeline Example Files/Mats/NPM661-664'
path_2='/Volumes/EEG Core HD/Pipeline For Olga/Pipeline Example Files/Mats/NPM661-664/SlSz'

#imports single file
path_3='/Volumes/EEG Core HD/Pipeline For Olga/Pipeline Example Files/Mats/NPM661-664/SlSz/NPM661-664 210711 070952_053.smrx m1 NPM661 SlSz.mat'
path_3='Y:/Brandon/Spike2_Pipeline/Mats/NPM661-664/SlSz/NPM661-664 210711 070952_053.smrx m1 NPM661 SlSz.mat'
path_3='Y:/Brandon/Spike2_Pipeline/Mats/NPM665-668/SlSz/NPM665-668 210711 190335_054.smrx m2 NPM666 SlSz.mat'

In [3]:
p.return_file_list_from_server(path_3)

['Y:/Brandon/Spike2_Pipeline/Mats/NPM665-668/SlSz/NPM665-668 210711 190335_054.smrx m2 NPM666 SlSz.mat']

In [4]:
p.extract_metadata(path_3)

{'Cohort': 'NPM665-668',
 'Mouse': 'm2',
 'Annotation Type': 'SlSz',
 'Date': '210711',
 'Time': '190335_054'}

In [5]:
dict=p.download_new_file(path_3)


In [6]:
d_dict, min_full_epochs = p.decimate_all_channels(dict)
d_dict=p.zscore_all_channels(d_dict)

In [7]:
d_dict

{'dec_ECog': array([ 0.29088643, -0.06855939, -0.6580078 , ..., -0.60099524,
        -1.4105169 , -2.5693393 ], dtype=float32),
 'dec_EMG': array([-3.9049275 ,  7.9915237 ,  2.483359  , ..., -1.211296  ,
        -0.7862996 ,  0.05005981], dtype=float32),
 'dec_HPC_L': array([ 3.1602461e-04,  8.7768853e-01,  1.5222915e+00, ...,
         2.0462518e+00, -2.4675387e-01,  7.1112899e-04], dtype=float32),
 'dec_HPC_R': array([0.15844232, 1.392502  , 1.5733238 , ..., 1.9235904 , 0.6010037 ,
        0.096587  ], dtype=float32)}

In [8]:
ordered_array=p.create_epochs(d_dict)

In [9]:
ordered_array[0]

array([[ 2.9088643e-01, -6.8559393e-02, -6.5800780e-01, ...,
         1.0410837e+00,  7.6740718e-01,  5.6476057e-01],
       [-3.9049275e+00,  7.9915237e+00,  2.4833591e+00, ...,
         3.0091482e-01, -6.9725847e-01,  3.4915036e-01],
       [ 3.1602461e-04,  8.7768853e-01,  1.5222915e+00, ...,
        -1.0702263e+00, -1.1130424e+00, -9.8853868e-01],
       [ 1.5844232e-01,  1.3925020e+00,  1.5733238e+00, ...,
        -6.1831534e-01, -1.5513086e+00, -7.1690381e-01]], dtype=float32)

In [10]:
X_test=StandardScaler().fit_transform(p.feature_generation(ordered_array))

In [11]:
X_test[0]

array([-2.71643902e+00, -1.50546065e-02, -9.42893001e-01, -5.41281230e-01,
        1.80828615e-01, -3.09314910e-01,  6.77439506e+00,  5.94934394e+00,
        3.67005251e+00, -2.91557381e-01, -1.29786758e+00,  1.54768861e-01,
        5.33817940e-01, -9.90451287e-01, -8.77152533e-01,  2.05870675e-01,
        7.01032454e-01,  1.70190174e+00,  1.52010653e+00, -5.08131782e-01,
        2.63284497e+01,  1.57548807e+00,  9.97864920e-01,  7.72578088e-01,
        1.80079722e-01,  1.02855653e+00,  1.26748761e+01,  1.07920586e+01,
        7.08305308e+00,  1.09985423e+00, -4.96604843e+00, -2.40429598e+00,
        1.23769142e+00,  6.15624564e-03, -3.61011522e-01, -6.80848811e-01,
       -4.39829472e-01,  6.93791251e-01,  6.32938084e-01,  4.49685191e-01,
        3.38468154e+00, -5.85734044e-01,  1.43196326e-01, -3.78704845e-03,
        6.81914478e-01, -4.63465074e-01,  7.04200794e+00,  6.70505443e+00,
        4.82747739e+00,  1.57256691e+00, -3.70764811e+00, -4.27246269e-01,
        8.26173623e-01, -

In [12]:
X_test.shape

(2160, 100)

In [13]:
dict.keys()

dict_keys(['V2_ECog', 'V2_EMG', 'V2_HPC_L', 'V2_HPC_R', 'V2_NPM666slsl', 'V2_NPM666szsz'])

In [14]:
import re
import numpy as np

In [17]:
scores_reindex=find_scores(dict)

Found: sl
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]
(2161, 4)


In [19]:
y_test=scores_reindex

In [20]:
X_predict=m.generate_x_sequences(X_test, 3)
y_predict=m.generate_y_sequences(y_test, 3)

In [22]:
from keras.models import load_model
model=load_model('../Models/SWISC 4 Channel and RMS.h5')

In [23]:
predictions = model.predict(X_predict)
y_pred = np.argmax(predictions, axis=1)
y_true = np.argmax(y_predict, axis=1)


accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
kappa = cohen_kappa_score(y_true, y_pred)
mcc = matthews_corrcoef(y_true, y_pred)

overview={
    'File Name': path.split('/')[-1],
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1 Score': f1,
    'Cohen Kappa': kappa,
    'MCC': mcc,
    # 'Log Loss': loss
}
    # Return as a dictionary
    

68/68 [==============================] - 4s 5ms/step


In [24]:
overview

{'File Name': 'Feats_Fourier_and_PSD',
 'Accuracy': 0.9512534818941504,
 'Precision': 0.8577914830407412,
 'Recall': 0.9387665998801857,
 'F1 Score': 0.8846047092589483,
 'Cohen Kappa': 0.8643055988864623,
 'MCC': 0.8646185575945551}